use std::env;
use std::path::PathBuf;

fn main() {
    create_rust_to_dart_bindings();
}

fn create_rust_to_dart_bindings() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    // let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let output_header = PathBuf::from(&crate_dir)
        .join("..")
        .join("src")
        .join("audiopc_ffi.h");

    // let language = if target_os == "android" {
    //     cbindgen::Language::Cxx
    // } else {
    //     cbindgen::Language::C
    // };

    // println!("Generating C bindings for Dart with cbindgen in {language:?} mode...");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_autogen_warning(
            "/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
    Legacy C header retained for compatibility. Primary Dart bindings now use flutter_rust_bridge.
*/",
        )
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output_header);
}