/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
    Legacy C header retained for compatibility. Primary Dart bindings now use flutter_rust_bridge.
*/

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * All public constants used across the crate.
 *
 * Centralised here so that feature-gating and per-platform tuning is easy.
 * Default number of seconds worth of decoded samples to keep buffered.
 */
#define DEFAULT_MAX_QUEUE_SECONDS 20

/**
 * Minimum allowed value for `max_queue_seconds`.
 */
#define MIN_MAX_QUEUE_SECONDS 1

/**
 * Maximum allowed value for `max_queue_seconds`.
 */
#define MAX_MAX_QUEUE_SECONDS 120

/**
 * How long (ms) the decode thread sleeps when the queue is full, before
 * retrying.  Keeping this short keeps latency low while still yielding to
 * the scheduler.
 */
#define DECODE_BACKPRESSURE_SLEEP_MS 2

/**
 * Number of seconds of audio kept in the visualizer ring buffer.
 */
#define DEFAULT_VISUALIZER_SECONDS 2

/**
 * FFT size used by `VisualizerProcessor`.  Must be a power of two.
 */
#define VISUALIZER_FFT_SIZE 2048

/**
 * Default number of output frequency bars for the spectrum visualizer.
 */
#define DEFAULT_VISUALIZER_BAR_COUNT 64

/**
 * Lowest frequency bucket shown on the visualizer (Hz).
 */
#define VISUALIZER_MIN_HZ 35.0

/**
 * Minimum allowed playback rate (0.5 = half speed).
 */
#define MIN_RATE 0.5

/**
 * Maximum allowed playback rate (2.0 = double speed).
 */
#define MAX_RATE 2.0

/**
 * How frequently (ms) the device watcher thread polls for device changes.
 * This value is a trade-off between responsiveness and CPU usage.
 */
#define DEVICE_POLL_INTERVAL_MS 2000

int32_t audiopc_default_output_sample_rate(void);

int32_t audiopc_default_output_channels(void);

int32_t audiopc_output_device_count(void);

int32_t audiopc_set_source_path(const char *path);

int32_t audiopc_set_source_url(const char *url);

int32_t audiopc_set_source_memory(const uint8_t *data, int32_t len);

int32_t audiopc_play(void);

int32_t audiopc_pause(void);

int32_t audiopc_stop(void);

int32_t audiopc_set_volume(double volume);

int32_t audiopc_set_rate(float rate);

float audiopc_get_rate(void);

int32_t audiopc_set_max_queue_seconds(int32_t seconds);

int32_t audiopc_get_max_queue_seconds(void);

int32_t audiopc_buffered_samples(void);

int32_t audiopc_buffered_millis(void);

int32_t audiopc_seek_millis(int32_t millis);

int32_t audiopc_duration_millis(void);

int32_t audiopc_position_millis(void);

int32_t audiopc_is_playing(void);

int32_t audiopc_get_player_state(void);

int32_t audiopc_visualizer_available_samples(void);

int32_t audiopc_visualizer_sample_rate(void);

int32_t audiopc_visualizer_channels(void);

int32_t audiopc_copy_visualizer_samples(float *buffer, int32_t max_samples);

int32_t audiopc_copy_visualizer_spectrum(float *buffer, int32_t max_bars);

int32_t audiopc_get_metadata(char *buffer, int32_t max_len, const char *path);

int32_t audiopc_get_thumbnail(uint8_t *buffer, int32_t max_len, const char *path);

int32_t audiopc_clear_filters(void);

int32_t audiopc_set_peak_filter(float center_hz, float gain_db, float q);

int32_t audiopc_set_low_shelf_filter(float cutoff_hz, float gain_db, float q);

int32_t audiopc_set_high_shelf_filter(float cutoff_hz, float gain_db, float q);

int32_t audiopc_set_band_pass_filter(float center_hz, float q);

int32_t audiopc_set_notch_filter(float center_hz, float q);

int32_t audiopc_set_lowpass_hz(double cutoff_hz, float q);

int32_t audiopc_set_high_pass_filter(float cutoff_hz, float q);
